name: delete-old-packages

on:
  push:
    branches:
      - 'master'

jobs:
  clean-ghcr:
    timeout-minutes: 5
    name: Delete old unused container images
    runs-on: ubuntu-latest

    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: learntrack*
          cut-off: One month ago UTC
          keep-at-least: 10
          skip-tags: v*
          account-type: org
          org-name: learn-track
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
